# Pandas数据结构

In [1]:
import pandas as pd

* Series

In [2]:
# 通过list构建Series
ser_obj = pd.Series(range(10, 20))
print(type(ser_obj))

<class 'pandas.core.series.Series'>


In [4]:
# 获取数据
print(type(ser_obj.values))

# 获取索引
print(type(ser_obj.index))

<class 'numpy.ndarray'>
<class 'pandas.indexes.range.RangeIndex'>


In [ ]:
# 预览数据
print(ser_obj.head(3))

In [ ]:
print(ser_obj)

In [ ]:
#通过索引获取数据
print(ser_obj[0])
print(ser_obj[8])

In [8]:
# 索引与数据的对应关系仍保持在数组运算的结果中
#print(ser_obj * 2)
print(ser_obj[ser_obj > 15])

6    16
7    17
8    18
9    19
dtype: int32


In [9]:
# 通过dict构建Series
year_data = {2001: 17.8, 2002: 20.1, 2003: 16.5}
ser_obj2 = pd.Series(year_data)
print(ser_obj2.head())
print(ser_obj2.index)

2001    17.8
2002    20.1
2003    16.5
dtype: float64
Int64Index([2001, 2002, 2003], dtype='int64')


In [10]:
# name属性
ser_obj2.name = 'temp'
ser_obj2.index.name = 'year'
print(ser_obj2.head())

year
2001    17.8
2002    20.1
2003    16.5
Name: temp, dtype: float64


* DataFrame

In [11]:
import numpy as np

# 通过ndarray构建DataFrame
array = np.random.randn(5,4)
print(array)

df_obj = pd.DataFrame(array)
print(df_obj.head())

[[-0.55625099  0.93442467  0.11535717  1.56342066]
 [ 0.64320193 -0.04893324 -1.31818906 -0.62097227]
 [ 1.66981493 -0.56092261 -0.84242506 -0.04470127]
 [ 1.35308608  0.4114026  -0.59249362  0.84416865]
 [ 1.7178888   2.28936201 -0.19930729 -1.02277666]]
          0         1         2         3
0 -0.556251  0.934425  0.115357  1.563421
1  0.643202 -0.048933 -1.318189 -0.620972
2  1.669815 -0.560923 -0.842425 -0.044701
3  1.353086  0.411403 -0.592494  0.844169
4  1.717889  2.289362 -0.199307 -1.022777


In [12]:
# 通过dict构建DataFrame
dict_data = {'A': 1., 
             'B': pd.Timestamp('20161217'),
             'C': pd.Series(1, index=list(range(4)),dtype='float32'),
             'D': np.array([3] * 4,dtype='int32'),
             'E' : pd.Categorical(["Python","Java","C++","C#"]),
             'F' : 'ChinaHadoop' }
#print dict_data
df_obj2 = pd.DataFrame(dict_data)
print(df_obj2.head())

     A          B    C  D       E            F
0  1.0 2016-12-17  1.0  3  Python  ChinaHadoop
1  1.0 2016-12-17  1.0  3    Java  ChinaHadoop
2  1.0 2016-12-17  1.0  3     C++  ChinaHadoop
3  1.0 2016-12-17  1.0  3      C#  ChinaHadoop


In [13]:
# 通过列索引获取列数据
print(df_obj2['A'])
print(type(df_obj2['A']))

print(df_obj2.A)

0    1.0
1    1.0
2    1.0
3    1.0
Name: A, dtype: float64
<class 'pandas.core.series.Series'>
0    1.0
1    1.0
2    1.0
3    1.0
Name: A, dtype: float64


In [14]:
# 增加列
df_obj2['G'] = df_obj2['D'] + 4
print(df_obj2.head())

     A          B    C  D       E            F  G
0  1.0 2016-12-17  1.0  3  Python  ChinaHadoop  7
1  1.0 2016-12-17  1.0  3    Java  ChinaHadoop  7
2  1.0 2016-12-17  1.0  3     C++  ChinaHadoop  7
3  1.0 2016-12-17  1.0  3      C#  ChinaHadoop  7


In [ ]:
# 删除列
del(df_obj2['G'] )
print(df_obj2.head())

* 索引对象 Index

In [ ]:
print(type(ser_obj.index))
print(type(df_obj2.index))

print(df_obj2.index)

In [ ]:
# 索引对象不可变
df_obj2.index[0] = 2